# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

language: r
warnings_are_errors: true
sudo: required


install:
  - ./travis-tool.sh install_github hadley/devtools
  - Rscript -e "devtools::install_github('yihui/knitr')"
  - Rscript -e "library(knitr); knit('README.Rmd')"

