language: r
r_github_packages: yihui/knitr
warnings_are_errors: true
sudo: required


install:
  - Rscript -e "devtools::install_github('yihui/knitr')"
  - Rscript -e "library(knitr); knit('README.Rmd')"

